import { notFound } from 'next/navigation';
import { readFile } from 'fs/promises';
import { compileMDX } from 'next-mdx-remote/rsc';
import remarkGfm from 'remark-gfm';
import rehypeSlug from 'rehype-slug';
import rehypeAutolinkHeadings from 'rehype-autolink-headings';
import rehypePrettyCode from 'rehype-pretty-code';
import { getAllDocPaths, getDocFilePath } from '@/lib/docs/static-paths';
import { extractHeadingsForTOC } from '@/lib/docs/heading-utils';
import { Callout } from '@/components/documentation/callout';
import { Card, CardGrid } from '@/components/documentation/card';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/documentation/tabs';
import { CodeBlockLazy } from '@/components/documentation/code-block-lazy';
import { OptimizedImage } from '@/components/documentation/optimized-image';
import { PagePrefetch } from '@/components/documentation/page-prefetch';
import { PageNavigation } from '@/components/documentation/page-navigation';
import { DocsLayoutClient } from '../docs-layout-client';

interface DocPageProps {
  params: Promise<{
    slug: string[];
  }>;
}

// Custom MDX components with lazy-loaded code blocks for performance
const components = {
  Callout,
  Card,
  CardGrid,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  pre: CodeBlockLazy,
  img: OptimizedImage,
};

/**
 * Generate static paths for all documentation pages
 * This enables static generation at build time
 */
export async function generateStaticParams() {
  const paths = await getAllDocPaths();
  return paths.map(({ slug }) => ({ slug }));
}

/**
 * Get MDX content for a given slug
 */
async function getDocContent(slug: string[]) {
  const filePath = getDocFilePath(slug);

  // Try .mdx first, then .md
  let content: string;
  try {
    content = await readFile(`${filePath}.mdx`, 'utf-8');
  } catch (mdxError) {
    try {
      content = await readFile(`${filePath}.md`, 'utf-8');
    } catch (mdError) {
      // Log the error in development
      if (process.env.NODE_ENV === 'development') {
        console.error(`Failed to read doc file for slug: ${slug.join('/')}`);
        console.error(`Tried paths: ${filePath}.mdx and ${filePath}.md`);
      }
      return null;
    }
  }

  return content;
}

/**
 * Documentation page component with static generation
 */
export default async function DocPage({ params }: DocPageProps) {
  const { slug } = await params;
  const content = await getDocContent(slug);

  if (!content) {
    notFound();
  }

  // Extract headings from raw MDX content before compilation
  // This ensures IDs match those generated by rehype-slug during rendering
  let headings;
  try {
    headings = extractHeadingsForTOC(content);
  } catch (error) {
    // Log error in development and continue without headings
    if (process.env.NODE_ENV === 'development') {
      console.error('[DocPage] Failed to extract headings:', error);
    }
    // Fallback to empty array - page will render without right sidebar
    headings = [];
  }

  // Compile MDX with plugins
  const { content: mdxContent, frontmatter } = await compileMDX({
    source: content,
    components,
    options: {
      parseFrontmatter: true,
      mdxOptions: {
        remarkPlugins: [remarkGfm],
        rehypePlugins: [
          rehypeSlug,
          [
            rehypeAutolinkHeadings,
            {
              behavior: 'wrap',
              properties: {
                className: ['anchor'],
              },
            },
          ],
          [
            rehypePrettyCode,
            {
              theme: {
                dark: 'github-dark',
                light: 'github-light',
              },
              keepBackground: false,
            },
          ],
        ],
      },
    },
  });

  return (
    <DocsLayoutClient headings={headings}>
      {/* Prefetch adjacent pages for faster navigation */}
      <PagePrefetch />
      
      <article className="prose prose-slate dark:prose-invert max-w-none">
        {frontmatter?.title && <h1>{frontmatter.title as string}</h1>}
        {mdxContent}
      </article>

      {/* Previous/Next page navigation */}
      <PageNavigation />
    </DocsLayoutClient>
  );
}

/**
 * Generate metadata for SEO
 */
export async function generateMetadata({ params }: DocPageProps) {
  const { slug } = await params;
  const content = await getDocContent(slug);

  if (!content) {
    return {
      title: 'Page Not Found',
    };
  }

  // Extract frontmatter for metadata
  const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
  let title = slug[slug.length - 1].replace(/-/g, ' ');
  let description = '';

  if (frontmatterMatch) {
    const frontmatter = frontmatterMatch[1];
    const titleMatch = frontmatter.match(/title:\s*(.+)/);
    const descMatch = frontmatter.match(/description:\s*(.+)/);

    if (titleMatch) title = titleMatch[1].replace(/['"]/g, '');
    if (descMatch) description = descMatch[1].replace(/['"]/g, '');
  }

  return {
    title: `${title} | SmartAPIForge Documentation`,
    description,
  };
}
