/**
 * FileReconciler Service
 * 
 * Reconciles file paths and handles naming conflicts for GitHub projects.
 * Handles case-insensitive matching and similar file name detection.
 * 
 * Requirements: 9.3, 9.4
 */

import type { IFileReconciler } from '../types/context-management';

/**
 * FileReconciler implementation
 * Provides path normalization and fuzzy file matching for reconciliation
 */
export class FileReconciler implements IFileReconciler {
  /**
   * Reconcile a generated file path against existing files
   * 
   * If the generated path matches an existing file (case-insensitive or similar name),
   * returns the existing file path. Otherwise returns the generated path.
   * 
   * Property 8: File Name Reconciliation
   * For any generated file path that differs only in case or separators from 
   * an existing file, the FileReconciler SHALL map it to the existing file.
   * 
   * @param generatedPath - The path generated by the AI
   * @param existingFiles - List of existing file paths in the project
   * @returns The reconciled path (existing file path if match found, otherwise generated path)
   */
  reconcile(generatedPath: string, existingFiles: string[]): string {
    // First, try to find an exact match (after normalization)
    const normalizedGenerated = this.normalizePath(generatedPath);
    
    for (const existingPath of existingFiles) {
      const normalizedExisting = this.normalizePath(existingPath);
      
      // Case-insensitive exact match
      if (normalizedGenerated.toLowerCase() === normalizedExisting.toLowerCase()) {
        return existingPath;
      }
    }
    
    // Try to find a similar file (fuzzy matching)
    const similarFile = this.findSimilarFile(generatedPath, existingFiles);
    if (similarFile) {
      return similarFile;
    }
    
    // No match found, return the generated path (normalized)
    return normalizedGenerated;
  }

  /**
   * Normalize a file path for consistent handling
   * 
   * - Converts backslashes to forward slashes
   * - Removes leading/trailing slashes
   * - Removes duplicate slashes
   * - Preserves the original case (normalization is case-preserving)
   * 
   * @param path - The path to normalize
   * @returns Normalized path
   */
  normalizePath(path: string): string {
    if (!path) {
      return '';
    }
    
    return path
      // Convert backslashes to forward slashes
      .replace(/\\/g, '/')
      // Remove duplicate slashes
      .replace(/\/+/g, '/')
      // Remove leading slash
      .replace(/^\//, '')
      // Remove trailing slash
      .replace(/\/$/, '')
      // Trim whitespace
      .trim();
  }

  /**
   * Find a similar file in the existing files list
   * 
   * Handles common naming variations:
   * - Case differences (HeroSection.tsx vs hero-section.tsx)
   * - Separator differences (hero-section vs heroSection vs hero_section)
   * - Extension variations (.tsx vs .ts vs .jsx vs .js)
   * 
   * @param path - The path to find a match for
   * @param existingFiles - List of existing file paths
   * @returns The matching existing file path, or null if no match
   */
  findSimilarFile(path: string, existingFiles: string[]): string | null {
    const normalizedPath = this.normalizePath(path);
    
    if (!normalizedPath || existingFiles.length === 0) {
      return null;
    }
    
    // Extract directory and filename
    const { dir, name, ext } = this.parsePath(normalizedPath);
    
    // Normalize the filename for comparison (convert to lowercase, remove separators)
    const normalizedName = this.normalizeFileName(name);
    
    // Find best match
    let bestMatch: string | null = null;
    let bestScore = 0;
    
    for (const existingPath of existingFiles) {
      const normalizedExisting = this.normalizePath(existingPath);
      const existingParsed = this.parsePath(normalizedExisting);
      
      // Calculate similarity score
      const score = this.calculateSimilarity(
        { dir, name: normalizedName, ext },
        { 
          dir: existingParsed.dir, 
          name: this.normalizeFileName(existingParsed.name), 
          ext: existingParsed.ext 
        }
      );
      
      if (score > bestScore && score >= 0.8) {
        bestScore = score;
        bestMatch = existingPath;
      }
    }
    
    return bestMatch;
  }

  /**
   * Parse a path into directory, name, and extension components
   */
  private parsePath(path: string): { dir: string; name: string; ext: string } {
    const lastSlash = path.lastIndexOf('/');
    const dir = lastSlash >= 0 ? path.substring(0, lastSlash) : '';
    const fullName = lastSlash >= 0 ? path.substring(lastSlash + 1) : path;
    
    // Handle files with multiple dots (e.g., component.test.tsx)
    const lastDot = fullName.lastIndexOf('.');
    const name = lastDot > 0 ? fullName.substring(0, lastDot) : fullName;
    const ext = lastDot > 0 ? fullName.substring(lastDot) : '';
    
    return { dir, name, ext };
  }

  /**
   * Normalize a filename for comparison
   * 
   * Converts various naming conventions to a common format:
   * - HeroSection -> herosection
   * - hero-section -> herosection
   * - hero_section -> herosection
   * - heroSection -> herosection
   */
  private normalizeFileName(name: string): string {
    return name
      // Convert to lowercase
      .toLowerCase()
      // Remove hyphens
      .replace(/-/g, '')
      // Remove underscores
      .replace(/_/g, '')
      // Remove dots (for files like component.test)
      .replace(/\./g, '');
  }

  /**
   * Calculate similarity score between two parsed paths
   * 
   * @returns Score between 0 and 1, where 1 is a perfect match
   */
  private calculateSimilarity(
    generated: { dir: string; name: string; ext: string },
    existing: { dir: string; name: string; ext: string }
  ): number {
    let score = 0;
    
    // Name match is most important (0.6 weight)
    if (generated.name === existing.name) {
      score += 0.6;
    } else if (this.isSubstringMatch(generated.name, existing.name)) {
      // Partial name match
      score += 0.3;
    }
    
    // Directory match (0.25 weight)
    if (generated.dir.toLowerCase() === existing.dir.toLowerCase()) {
      score += 0.25;
    } else if (this.directoriesOverlap(generated.dir, existing.dir)) {
      // Partial directory match
      score += 0.15;
    }
    
    // Extension match (0.15 weight)
    if (this.extensionsMatch(generated.ext, existing.ext)) {
      score += 0.15;
    }
    
    return score;
  }

  /**
   * Check if one string is a substring of another
   */
  private isSubstringMatch(a: string, b: string): boolean {
    if (!a || !b) return false;
    return a.includes(b) || b.includes(a);
  }

  /**
   * Check if directories have overlapping components
   */
  private directoriesOverlap(dir1: string, dir2: string): boolean {
    if (!dir1 || !dir2) return false;
    
    const parts1 = dir1.toLowerCase().split('/').filter(Boolean);
    const parts2 = dir2.toLowerCase().split('/').filter(Boolean);
    
    // Check if any directory component matches
    return parts1.some(p => parts2.includes(p));
  }

  /**
   * Check if extensions are compatible
   * 
   * Considers .tsx, .ts, .jsx, .js as compatible React/JS extensions
   */
  private extensionsMatch(ext1: string, ext2: string): boolean {
    if (ext1.toLowerCase() === ext2.toLowerCase()) {
      return true;
    }
    
    // Compatible extension groups
    const jsExtensions = ['.js', '.jsx', '.ts', '.tsx'];
    const cssExtensions = ['.css', '.scss', '.sass', '.less'];
    
    const ext1Lower = ext1.toLowerCase();
    const ext2Lower = ext2.toLowerCase();
    
    // Check if both are in the same extension group
    if (jsExtensions.includes(ext1Lower) && jsExtensions.includes(ext2Lower)) {
      return true;
    }
    if (cssExtensions.includes(ext1Lower) && cssExtensions.includes(ext2Lower)) {
      return true;
    }
    
    return false;
  }
}

// Export singleton instance
export const fileReconciler = new FileReconciler();
