/**
 * Swagger UI Generator Service
 * 
 * Generates code for interactive Swagger/OpenAPI documentation pages
 * that can be included in user-generated API projects.
 * 
 * This service generates:
 * - Next.js page component for Swagger UI (`app/api-docs/page.tsx`)
 * - API route to serve OpenAPI spec (`app/api/openapi/route.ts`)
 * - Static OpenAPI spec file (`public/openapi.yaml`)
 * 
 * Requirements: 3.9, 3.10
 */

// =============================================================================
// Types and Interfaces
// =============================================================================

export interface SwaggerUIConfig {
  /** Path to fetch the OpenAPI spec (e.g., '/api/openapi') */
  specPath: string;
  /** URL path for the docs page (e.g., '/api-docs') */
  docsPath: string;
  /** Title for the documentation page */
  title: string;
  /** Theme for Swagger UI */
  theme?: 'light' | 'dark';
  /** Whether to enable "Try it out" functionality */
  tryItOutEnabled?: boolean;
  /** Default expansion level for operations */
  docExpansion?: 'list' | 'full' | 'none';
  /** Whether to show request duration */
  showRequestDuration?: boolean;
  /** Whether to enable filtering */
  enableFilter?: boolean;
  /** Whether to deep link to operations */
  deepLinking?: boolean;
}

export interface SwaggerGeneratorResult {
  /** The Swagger UI page component code */
  docsPage: string;
  /** The API route code to serve the OpenAPI spec */
  specRoute: string;
  /** The static OpenAPI spec (YAML format) */
  specYaml: string;
  /** Package.json dependencies to add */
  dependencies: Record<string, string>;
  /** File paths for the generated files */
  filePaths: SwaggerFilePaths;
}

export interface SwaggerFilePaths {
  /** Path for the docs page (e.g., 'app/api-docs/page.tsx') */
  docsPage: string;
  /** Path for the spec route (e.g., 'app/api/openapi/route.ts') */
  specRoute: string;
  /** Path for the static spec file (e.g., 'public/openapi.yaml') */
  specYaml: string;
  /** Path for the layout file (e.g., 'app/api-docs/layout.tsx') */
  docsLayout?: string;
}

export interface GenerateSwaggerOptions {
  /** Name of the API (used in title and metadata) */
  apiName: string;
  /** The OpenAPI spec content (YAML or JSON string) */
  specContent: string;
  /** Custom configuration for Swagger UI */
  config?: Partial<SwaggerUIConfig>;
  /** Base path for generated files (default: '') */
  basePath?: string;
  /** Whether to include a layout file */
  includeLayout?: boolean;
}

// =============================================================================
// Default Configuration
// =============================================================================

const DEFAULT_CONFIG: SwaggerUIConfig = {
  specPath: '/api/openapi',
  docsPath: '/api-docs',
  title: 'API Documentation',
  theme: 'light',
  tryItOutEnabled: true,
  docExpansion: 'list',
  showRequestDuration: true,
  enableFilter: true,
  deepLinking: true,
};

const SWAGGER_DEPENDENCIES: Record<string, string> = {
  'swagger-ui-react': '^5.11.0',
};

// =============================================================================
// Code Generators
// =============================================================================

/**
 * Generate the Swagger UI page component for Next.js App Router
 * 
 * @param config - Swagger UI configuration
 * @returns The page component code as a string
 */
export function generateSwaggerUIPage(config: SwaggerUIConfig): string {
  const {
    specPath,
    title,
    theme = 'light',
    docExpansion = 'list',
    showRequestDuration = true,
    enableFilter = true,
    deepLinking = true,
  } = config;

  const bgColor = theme === 'dark' ? 'bg-gray-900' : 'bg-white';
  
  return `'use client';

/**
 * API Documentation Page
 * 
 * Interactive Swagger UI for ${title}
 * Generated by SmartAPIForge
 */

import dynamic from 'next/dynamic';
import 'swagger-ui-react/swagger-ui.css';

// Dynamically import Swagger UI to avoid SSR issues
const SwaggerUI = dynamic(() => import('swagger-ui-react'), { 
  ssr: false,
  loading: () => (
    <div className="flex items-center justify-center min-h-screen">
      <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
    </div>
  ),
});

export default function ApiDocsPage() {
  return (
    <div className="min-h-screen ${bgColor}">
      <SwaggerUI 
        url="${specPath}"
        docExpansion="${docExpansion}"
        defaultModelsExpandDepth={1}
        displayRequestDuration={${showRequestDuration}}
        filter={${enableFilter}}
        showExtensions={true}
        showCommonExtensions={true}
        deepLinking={${deepLinking}}
        tryItOutEnabled={true}
      />
    </div>
  );
}
`;
}

/**
 * Generate the API route to serve the OpenAPI spec
 * 
 * @param specContent - The OpenAPI spec content (YAML or JSON)
 * @param format - The format to serve ('yaml' or 'json')
 * @returns The route handler code as a string
 */
export function generateOpenAPIRoute(
  specContent: string,
  format: 'yaml' | 'json' = 'yaml'
): string {
  // Escape the spec content for embedding in code
  const escapedContent = JSON.stringify(specContent);
  const contentType = format === 'yaml' 
    ? 'application/x-yaml' 
    : 'application/json';

  return `/**
 * OpenAPI Specification Route
 * 
 * Serves the OpenAPI spec for this API.
 * Access at: GET /api/openapi
 * 
 * Generated by SmartAPIForge
 */

import { NextResponse } from 'next/server';

const openAPISpec = ${escapedContent};

export async function GET() {
  return new NextResponse(openAPISpec, {
    status: 200,
    headers: {
      'Content-Type': '${contentType}',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}

export async function OPTIONS() {
  return new NextResponse(null, {
    status: 204,
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    },
  });
}
`;
}

/**
 * Generate a layout file for the API docs page
 * 
 * @param title - The page title
 * @returns The layout component code as a string
 */
export function generateDocsLayout(title: string): string {
  return `/**
 * API Documentation Layout
 * 
 * Layout wrapper for the Swagger UI documentation page.
 * Generated by SmartAPIForge
 */

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${title}',
  description: 'Interactive API documentation powered by Swagger UI',
};

export default function ApiDocsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="api-docs-container">
      {children}
    </div>
  );
}
`;
}

/**
 * Generate a simple README for the API documentation
 * 
 * @param apiName - Name of the API
 * @param docsPath - Path to the docs page
 * @returns The README content as a string
 */
export function generateDocsReadme(apiName: string, docsPath: string): string {
  return `# ${apiName} API Documentation

## Interactive Documentation

This API includes interactive Swagger UI documentation.

### Accessing the Documentation

- **Swagger UI**: [${docsPath}](${docsPath})
- **OpenAPI Spec**: [/api/openapi](/api/openapi)

### Features

- **Try it out**: Test API endpoints directly from the browser
- **Request/Response Examples**: See example payloads for each endpoint
- **Schema Definitions**: View all data models and their properties
- **Authentication**: Configure authentication headers for testing

### Using the Documentation

1. Navigate to the Swagger UI page
2. Click on an endpoint to expand it
3. Click "Try it out" to enable testing
4. Fill in the required parameters
5. Click "Execute" to send the request
6. View the response below

### OpenAPI Specification

The raw OpenAPI specification is available at \`/api/openapi\` in YAML format.
You can use this spec with other tools like:

- Postman (import collection)
- Insomnia
- OpenAPI Generator (generate client SDKs)

---

*Generated by SmartAPIForge*
`;
}

// =============================================================================
// Main Generator Functions
// =============================================================================

/**
 * Generate all Swagger UI files for an API project
 * 
 * This is the main entry point for generating Swagger documentation.
 * It creates all necessary files for a complete Swagger UI integration.
 * 
 * @param options - Generation options
 * @returns All generated files and metadata
 */
export function generateSwaggerFiles(
  options: GenerateSwaggerOptions
): SwaggerGeneratorResult {
  const {
    apiName,
    specContent,
    config = {},
    basePath = '',
    includeLayout = true,
  } = options;

  // Merge with default config
  const fullConfig: SwaggerUIConfig = {
    ...DEFAULT_CONFIG,
    ...config,
    title: config.title || `${apiName} API Documentation`,
  };

  // Generate file paths
  const filePaths: SwaggerFilePaths = {
    docsPage: joinPath(basePath, 'app/api-docs/page.tsx'),
    specRoute: joinPath(basePath, 'app/api/openapi/route.ts'),
    specYaml: joinPath(basePath, 'public/openapi.yaml'),
  };

  if (includeLayout) {
    filePaths.docsLayout = joinPath(basePath, 'app/api-docs/layout.tsx');
  }

  // Generate all files
  const result: SwaggerGeneratorResult = {
    docsPage: generateSwaggerUIPage(fullConfig),
    specRoute: generateOpenAPIRoute(specContent),
    specYaml: specContent,
    dependencies: { ...SWAGGER_DEPENDENCIES },
    filePaths,
  };

  return result;
}

/**
 * Generate a complete set of documentation files including README
 * 
 * @param options - Generation options
 * @returns Object with all file contents keyed by path
 */
export function generateCompleteSwaggerDocs(
  options: GenerateSwaggerOptions
): Record<string, string> {
  const result = generateSwaggerFiles(options);
  const { apiName, basePath = '' } = options;

  const files: Record<string, string> = {
    [result.filePaths.docsPage]: result.docsPage,
    [result.filePaths.specRoute]: result.specRoute,
    [result.filePaths.specYaml]: result.specYaml,
  };

  // Add layout if path exists
  if (result.filePaths.docsLayout) {
    files[result.filePaths.docsLayout] = generateDocsLayout(
      `${apiName} API Documentation`
    );
  }

  // Add README
  const readmePath = joinPath(basePath, 'docs/API_DOCS.md');
  files[readmePath] = generateDocsReadme(apiName, '/api-docs');

  return files;
}

// =============================================================================
// Utility Functions
// =============================================================================

/**
 * Join path segments, handling empty base paths
 */
function joinPath(base: string, path: string): string {
  if (!base) return path;
  return `${base.replace(/\/$/, '')}/${path.replace(/^\//, '')}`;
}

/**
 * Get the list of dependencies required for Swagger UI
 * 
 * @returns Object with package names and versions
 */
export function getSwaggerDependencies(): Record<string, string> {
  return { ...SWAGGER_DEPENDENCIES };
}

/**
 * Check if a project has Swagger UI dependencies installed
 * 
 * @param packageJson - The package.json content as an object
 * @returns Whether swagger-ui-react is in dependencies
 */
export function hasSwaggerDependency(
  packageJson: { dependencies?: Record<string, string> }
): boolean {
  return !!packageJson.dependencies?.['swagger-ui-react'];
}

/**
 * Get the package.json additions needed for Swagger UI
 * 
 * @returns Partial package.json object with dependencies
 */
export function getPackageJsonAdditions(): { dependencies: Record<string, string> } {
  return {
    dependencies: { ...SWAGGER_DEPENDENCIES },
  };
}

/**
 * Generate a minimal Swagger UI page (without extra features)
 * 
 * @param specUrl - URL to fetch the OpenAPI spec
 * @returns Minimal page component code
 */
export function generateMinimalSwaggerPage(specUrl: string): string {
  return `'use client';

import dynamic from 'next/dynamic';
import 'swagger-ui-react/swagger-ui.css';

const SwaggerUI = dynamic(() => import('swagger-ui-react'), { ssr: false });

export default function ApiDocsPage() {
  return <SwaggerUI url="${specUrl}" />;
}
`;
}

/**
 * Generate an inline spec route (spec embedded in the route file)
 * Useful for smaller specs that don't need a separate file
 * 
 * @param spec - The OpenAPI spec object
 * @returns Route handler code with embedded spec
 */
export function generateInlineSpecRoute(spec: object): string {
  const specJson = JSON.stringify(spec, null, 2);
  
  return `/**
 * OpenAPI Specification Route (Inline)
 * 
 * Serves the OpenAPI spec embedded directly in this file.
 * Generated by SmartAPIForge
 */

import { NextResponse } from 'next/server';

const openAPISpec = ${specJson};

export async function GET() {
  return NextResponse.json(openAPISpec, {
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Cache-Control': 'public, max-age=3600',
    },
  });
}
`;
}
