# =============================================================================
# SmartAPIForge Next.js Template Image
# =============================================================================
# This Dockerfile creates a pre-built Next.js environment with all common
# dependencies pre-installed for fast project scaffolding.
#
# Uses Next.js 15 (stable) with Tailwind CSS v4 (included by default).
#
# Build:
#   docker build -f docker/nextjs-template.Dockerfile -t yourusername/smartapiforge-nextjs-template:latest .
#
# Push to Docker Hub:
#   docker push yourusername/smartapiforge-nextjs-template:latest
#
# Then set in .env.local:
#   DAYTONA_TEMPLATE_ID=yourusername/smartapiforge-nextjs-template:latest
# =============================================================================

FROM node:22-bookworm

# Install pnpm globally
RUN npm install -g pnpm@latest

# Set working directory
WORKDIR /workspace

# Create Next.js 15 project structure (includes Tailwind v4 by default)
# Use yes | to auto-confirm any prompts
RUN yes | npx create-next-app@15 . \
    --typescript \
    --tailwind \
    --eslint \
    --app \
    --src-dir=false \
    --import-alias="@/*" \
    --use-pnpm \
    --no-git \
    --turbopack || true

# Check if create-next-app succeeded, if not create manually
RUN if [ ! -f /workspace/package.json ]; then \
    echo "create-next-app failed, creating project manually..." && \
    pnpm init && \
    pnpm add next@15 react@19 react-dom@19 && \
    pnpm add -D typescript @types/node @types/react @types/react-dom tailwindcss@4 @tailwindcss/postcss@4 eslint eslint-config-next; \
    fi

# Verify package.json exists
RUN ls -la /workspace && cat /workspace/package.json | head -30

# Create app directory structure if it doesn't exist
RUN mkdir -p app lib components/ui hooks public

# Create app/globals.css with Tailwind v4 syntax
RUN printf '@import "tailwindcss";\n\n:root {\n  --background: #ffffff;\n  --foreground: #171717;\n}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n    --background: #0a0a0a;\n    --foreground: #ededed;\n  }\n}\n\nbody {\n  color: var(--foreground);\n  background: var(--background);\n  font-family: Arial, Helvetica, sans-serif;\n}\n' > app/globals.css

# Create app/layout.tsx
RUN printf 'import type { Metadata } from "next";\nimport { Inter } from "next/font/google";\nimport "./globals.css";\n\nconst inter = Inter({ subsets: ["latin"] });\n\nexport const metadata: Metadata = {\n  title: "Create Next App",\n  description: "Generated by create next app",\n};\n\nexport default function RootLayout({\n  children,\n}: Readonly<{\n  children: React.ReactNode;\n}>) {\n  return (\n    <html lang="en">\n      <body className={inter.className}>{children}</body>\n    </html>\n  );\n}\n' > app/layout.tsx

# Create app/page.tsx
RUN printf 'export default function Home() {\n  return (\n    <main className="flex min-h-screen flex-col items-center justify-center p-24">\n      <h1 className="text-4xl font-bold">SmartAPIForge Template</h1>\n      <p className="mt-4 text-gray-600">\n        Pre-built template with all dependencies installed.\n      </p>\n    </main>\n  );\n}\n' > app/page.tsx

# Create postcss.config.mjs for Tailwind v4
RUN printf 'const config = {\n  plugins: {\n    "@tailwindcss/postcss": {},\n  },\n};\n\nexport default config;\n' > postcss.config.mjs

# Create next.config.ts
RUN printf 'import type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {\n  /* config options here */\n};\n\nexport default nextConfig;\n' > next.config.ts

# Create tsconfig.json if it doesn't exist
RUN if [ ! -f /workspace/tsconfig.json ]; then \
    printf '{\n  "compilerOptions": {\n    "lib": ["dom", "dom.iterable", "esnext"],\n    "allowJs": true,\n    "skipLibCheck": true,\n    "strict": true,\n    "noEmit": true,\n    "esModuleInterop": true,\n    "module": "esnext",\n    "moduleResolution": "bundler",\n    "resolveJsonModule": true,\n    "isolatedModules": true,\n    "jsx": "preserve",\n    "incremental": true,\n    "plugins": [{ "name": "next" }],\n    "paths": { "@/*": ["./*"] }\n  },\n  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],\n  "exclude": ["node_modules"]\n}\n' > tsconfig.json; \
    fi

# Create lib/utils.ts for shadcn
RUN printf 'import { type ClassValue, clsx } from "clsx";\nimport { twMerge } from "tailwind-merge";\n\nexport function cn(...inputs: ClassValue[]) {\n  return twMerge(clsx(inputs));\n}\n' > lib/utils.ts

# Install UI libraries (shadcn dependencies)
RUN pnpm add class-variance-authority clsx tailwind-merge lucide-react

# Install Radix UI primitives (for shadcn/ui)
RUN pnpm add \
    @radix-ui/react-accordion \
    @radix-ui/react-alert-dialog \
    @radix-ui/react-aspect-ratio \
    @radix-ui/react-avatar \
    @radix-ui/react-checkbox \
    @radix-ui/react-collapsible \
    @radix-ui/react-context-menu \
    @radix-ui/react-dialog \
    @radix-ui/react-dropdown-menu \
    @radix-ui/react-hover-card \
    @radix-ui/react-label \
    @radix-ui/react-menubar \
    @radix-ui/react-navigation-menu \
    @radix-ui/react-popover \
    @radix-ui/react-progress \
    @radix-ui/react-radio-group \
    @radix-ui/react-scroll-area \
    @radix-ui/react-select \
    @radix-ui/react-separator \
    @radix-ui/react-slider \
    @radix-ui/react-slot \
    @radix-ui/react-switch \
    @radix-ui/react-tabs \
    @radix-ui/react-toast \
    @radix-ui/react-toggle \
    @radix-ui/react-toggle-group \
    @radix-ui/react-tooltip

# Install animation libraries
RUN pnpm add framer-motion gsap lottie-react

# Install data/state management libraries
RUN pnpm add @tanstack/react-query zustand zod react-hook-form @hookform/resolvers

# Install utility libraries
RUN pnpm add date-fns axios lodash-es
RUN pnpm add -D @types/lodash-es

# Create components.json for shadcn
RUN printf '{\n  "$schema": "https://ui.shadcn.com/schema.json",\n  "style": "default",\n  "rsc": true,\n  "tsx": true,\n  "tailwind": {\n    "config": "",\n    "css": "app/globals.css",\n    "baseColor": "slate",\n    "cssVariables": true,\n    "prefix": ""\n  },\n  "aliases": {\n    "components": "@/components",\n    "utils": "@/lib/utils",\n    "ui": "@/components/ui",\n    "lib": "@/lib",\n    "hooks": "@/hooks"\n  }\n}\n' > components.json

# Create public directory with placeholder
RUN echo 'Placeholder for static assets' > public/placeholder.txt

# Final verification - list all files in workspace
RUN echo "=== Final workspace contents ===" && \
    find /workspace -maxdepth 3 -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.json" -o -name "*.css" -o -name "*.mjs" \) | head -30

# Expose Next.js dev server port
EXPOSE 3000

# Default command - don't start dev server automatically
# The server will be started by the application after files are written
CMD ["tail", "-f", "/dev/null"]
