/**
 * Template Files Configuration
 * 
 * These are the essential files that exist in the pre-built Next.js template.
 * When the Daytona SDK fails to read files from the sandbox, we use these
 * as the initial file snapshot so the AI knows what files exist.
 * 
 * This ensures the preview works even if file reading fails.
 */

import type { FileSnapshotData } from '../types/database';

/**
 * Essential Next.js template files with their content
 * These match what's created by the Dockerfile
 */
export const TEMPLATE_FILES: FileSnapshotData = {
  'package.json': {
    content: `{
  "name": "nextjs-template",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbopack",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "15.5.9",
    "react": "^19.1.0",
    "react-dom": "^19.1.0",
    "class-variance-authority": "latest",
    "clsx": "latest",
    "tailwind-merge": "latest",
    "lucide-react": "latest",
    "@radix-ui/react-accordion": "latest",
    "@radix-ui/react-alert-dialog": "latest",
    "@radix-ui/react-avatar": "latest",
    "@radix-ui/react-checkbox": "latest",
    "@radix-ui/react-dialog": "latest",
    "@radix-ui/react-dropdown-menu": "latest",
    "@radix-ui/react-label": "latest",
    "@radix-ui/react-popover": "latest",
    "@radix-ui/react-progress": "latest",
    "@radix-ui/react-select": "latest",
    "@radix-ui/react-separator": "latest",
    "@radix-ui/react-slider": "latest",
    "@radix-ui/react-slot": "latest",
    "@radix-ui/react-switch": "latest",
    "@radix-ui/react-tabs": "latest",
    "@radix-ui/react-toast": "latest",
    "@radix-ui/react-tooltip": "latest",
    "framer-motion": "latest",
    "gsap": "latest",
    "lottie-react": "latest",
    "@tanstack/react-query": "latest",
    "zustand": "latest",
    "zod": "latest",
    "react-hook-form": "latest",
    "@hookform/resolvers": "latest",
    "date-fns": "latest",
    "axios": "latest",
    "lodash-es": "latest"
  },
  "devDependencies": {
    "typescript": "latest",
    "@types/node": "latest",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "@types/lodash-es": "latest",
    "@tailwindcss/postcss": "^4.0.0",
    "tailwindcss": "^4.0.0",
    "eslint": "latest",
    "eslint-config-next": "latest"
  }
}`,
    language: 'json',
    size: 1500,
  },

  'tsconfig.json': {
    content: `{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}`,
    language: 'json',
    size: 500,
  },

  'next.config.ts': {
    content: `import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
};

export default nextConfig;`,
    language: 'typescript',
    size: 120,
  },

  'postcss.config.mjs': {
    content: `/** @type {import('postcss-load-config').Config} */
const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;`,
    language: 'javascript',
    size: 150,
  },

  'next-env.d.ts': {
    content: `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.`,
    language: 'typescript',
    size: 200,
  },

  'app/layout.tsx': {
    content: `import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}`,
    language: 'typescript',
    size: 500,
  },

  'app/page.tsx': {
    content: `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to Next.js</h1>
      <p className="mt-4 text-muted-foreground">
        Start editing app/page.tsx to customize this page.
      </p>
    </main>
  );
}`,
    language: 'typescript',
    size: 300,
  },

  'app/globals.css': {
    content: `@import "tailwindcss";

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: Arial, Helvetica, sans-serif;
}`,
    language: 'css',
    size: 300,
  },

  'lib/utils.ts': {
    content: `import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}`,
    language: 'typescript',
    size: 150,
  },

  'components.json': {
    content: `{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "app/globals.css",
    "baseColor": "slate",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "hooks": "@/hooks"
  }
}`,
    language: 'json',
    size: 400,
  },

  '.gitignore': {
    content: `# dependencies
/node_modules
/.pnp
.pnp.js
.yarn/install-state.gz

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts`,
    language: 'plaintext',
    size: 350,
  },

  'README.md': {
    content: `# Next.js Project

This is a [Next.js](https://nextjs.org) project bootstrapped with SmartAPIForge.

## Getting Started

First, run the development server:

\`\`\`bash
npm run dev
# or
yarn dev
# or
pnpm dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

You can start editing the page by modifying \`app/page.tsx\`. The page auto-updates as you edit the file.

## Learn More

To learn more about Next.js, take a look at the following resources:

- [Next.js Documentation](https://nextjs.org/docs)
- [Learn Next.js](https://nextjs.org/learn)
`,
    language: 'markdown',
    size: 600,
  },

  'eslint.config.mjs': {
    content: `import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;`,
    language: 'javascript',
    size: 400,
  },

  'public/placeholder.txt': {
    content: `This is a placeholder file for the public directory.
Add your static assets here (images, fonts, etc.)`,
    language: 'plaintext',
    size: 100,
  },

  'components/ui/.gitkeep': {
    content: `# This directory is for shadcn/ui components
# Add components using: npx shadcn@latest add <component>`,
    language: 'plaintext',
    size: 80,
  },

  'hooks/.gitkeep': {
    content: `# This directory is for custom React hooks`,
    language: 'plaintext',
    size: 50,
  },
};

/**
 * Get the default template files
 * Use this when Daytona SDK fails to read files from the sandbox
 */
export function getDefaultTemplateFiles(): FileSnapshotData {
  return { ...TEMPLATE_FILES };
}

/**
 * Get the list of template file paths
 */
export function getTemplateFilePaths(): string[] {
  return Object.keys(TEMPLATE_FILES);
}

/**
 * Calculate total size of template files
 */
export function getTemplateTotalSize(): number {
  return Object.values(TEMPLATE_FILES).reduce((sum, file) => sum + file.size, 0);
}
